baseURL = 'fire-shop.netlify.app/'
languageCode = 'en-us'
title = 'Fireshop'
enableRobotsTXT = true

[outputs]
home = ["HTML", "RSS"]

[params]
mainSections = ["hoodies", "kids", "mens", "ladys", "jewellery", "shoals"]

params = ["tags"]

[markup.goldmark.renderer]
unsafe= true

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = false
    noHl = false
    style = 'monokai'
    tabWidth = 4