name: Build Fireshop

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
      VITE_SUPABASE_LOCAL: ${{ secrets.VITE_SUPABASE_LOCAL }}
      VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
      VITE_LOCAL_CART: ${{ secrets.VITE_LOCAL_CART }}
      VITE_LOCAL_ORDER: ${{ secrets.VITE_LOCAL_ORDER }}
      VITE_LOCAL_KEY: ${{ secrets.VITE_LOCAL_KEY }}
      VITE_REVOLT_EMAIL: ${{ secrets.VITE_REVOLT_EMAIL }}
      VITE_REVOLT_PASS: ${{ secrets.VITE_REVOLT_PASS }}
      VITE_REVOLT_ERROR: ${{ secrets.VITE_REVOLT_ERROR }}
      VITE_REVOLT_AUTH: ${{ secrets.VITE_REVOLT_AUTH }}
      VITE_REVOLT_REVIEW: ${{ secrets.VITE_REVOLT_REVIEW }}
      VITE_REVOLT_ORDERS: ${{ secrets.VITE_REVOLT_ORDERS }}
      VITE_HOOK_SUPA: ${{ secrets.VITE_HOOK_SUPA }}
      VITE_HOOK_REVIEW: ${{ secrets.VITE_HOOK_REVIEW }}
      VITE_HOOK_ORDER: ${{ secrets.VITE_HOOK_ORDER }}
      VITE_HOOK_AUTH: ${{ secrets.VITE_HOOK_AUTH }}
      VITE_OPEN_ROUTE: ${{ secrets.VITE_OPEN_ROUTE }}
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 19.4

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.109.0"
          extended: true

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: rm pnpm-lock.yaml && pnpm i

      - name: Synk Setup
        uses: snyk/actions/setup@master

      - name: Go Setup
        uses: actions/setup-go@v1
        with:
          go-version: "1.13"

      - name: Snyk test
        run: snyk test

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        with:
          command: monitor

      - run: mkdir ./static/svelte; touch static/svelte/index.html; npm run build
